// generated from content/components by scripts/gen - do not hand-edit types
import type { LucideIcon } from 'lucide-react'
import { Activity, AlarmClock, Anchor, Archive, ArrowLeftRight, Atom, BarChart3, Bell, BellRing, Blocks, Box, Braces, BrainCircuit, BrickWall, Cable, CalendarClock, CircleDot, Clapperboard, CloudCog, Cog, Container, CreditCard, Crown, Database, Droplets, Earth, Expand, FileSearch, Fingerprint, Flame, FolderOpen, Gauge, GitCommit, GitFork, Globe, HardDrive, Hash, History, Inbox, KeyRound, Landmark, Layers, Leaf, ListOrdered, Lock, Mail, Megaphone, MemoryStick, MessagesSquare, Monitor, Network, Orbit, Package, Paperclip, Plug, PlugZap, Puzzle, Radio, RadioTower, RefreshCcw, RotateCcw, Route, Router, Satellite, Scale, ScrollText, Search, Send, Server, Share2, Shield, ShieldCheck, Shuffle, Signpost, Smartphone, Sparkles, Split, ToggleLeft, TrendingDown, Warehouse, Waves, Wind, Wrench, Zap } from 'lucide-react'

export interface NodeVisual {
  abbr: string
  icon: LucideIcon
  color: string
}

export const NODE_VISUALS: Record<string, NodeVisual> = {
  'airflow': { abbr: 'AF', icon: CalendarClock, color: '#0d9488' },
  'alert_manager': { abbr: 'ALR', icon: BellRing, color: '#0891b2' },
  'api': { abbr: 'API', icon: Server, color: '#2563eb' },
  'api_gateway': { abbr: 'GW', icon: Router, color: '#2563eb' },
  'autoscaling_group': { abbr: 'ASG', icon: Expand, color: '#7c3aed' },
  'backpressure': { abbr: 'BPR', icon: TrendingDown, color: '#64748b' },
  'block_storage': { abbr: 'BLK', icon: HardDrive, color: '#059669' },
  'bulkhead': { abbr: 'BLKH', icon: BrickWall, color: '#64748b' },
  'cassandra': { abbr: 'CS', icon: CircleDot, color: '#059669' },
  'cdc_pipeline': { abbr: 'CDC', icon: RefreshCcw, color: '#0d9488' },
  'cdn': { abbr: 'CDN', icon: Globe, color: '#7c3aed' },
  'circuit_breaker': { abbr: 'CB', icon: ToggleLeft, color: '#64748b' },
  'clickhouse': { abbr: 'CH', icon: BarChart3, color: '#0f766e' },
  'client': { abbr: 'CL', icon: Monitor, color: '#64748b' },
  'cockroachdb': { abbr: 'CRDB', icon: HardDrive, color: '#059669' },
  'cqrs': { abbr: 'CQRS', icon: Split, color: '#64748b' },
  'cron_scheduler': { abbr: 'CRON', icon: AlarmClock, color: '#4338ca' },
  'data_warehouse': { abbr: 'DWH', icon: Warehouse, color: '#0f766e' },
  'distributed_lock': { abbr: 'LCK', icon: Lock, color: '#6d28d9' },
  'dns': { abbr: 'DNS', icon: Signpost, color: '#2563eb' },
  'dynamodb': { abbr: 'DDB', icon: CloudCog, color: '#059669' },
  'elasticsearch': { abbr: 'ES', icon: Search, color: '#0f766e' },
  'email_service': { abbr: 'MAIL', icon: Mail, color: '#ea580c' },
  'embeddings_model': { abbr: 'EMB', icon: Atom, color: '#9333ea' },
  'event_bus': { abbr: 'EB', icon: Cable, color: '#d97706' },
  'event_sourcing': { abbr: 'EVT', icon: RotateCcw, color: '#64748b' },
  'fanout_service': { abbr: 'FAN', icon: Megaphone, color: '#db2777' },
  'feature_store': { abbr: 'FEAT', icon: Puzzle, color: '#c026d3' },
  'file_storage': { abbr: 'FS', icon: FolderOpen, color: '#059669' },
  'flink': { abbr: 'FLK', icon: Droplets, color: '#0d9488' },
  'global_load_balancer': { abbr: 'GLB', icon: Earth, color: '#2563eb' },
  'graphql_gateway': { abbr: 'GQL', icon: GitFork, color: '#4f46e5' },
  'grpc': { abbr: 'gRPC', icon: PlugZap, color: '#4f46e5' },
  'id_generator': { abbr: 'SNOW', icon: Hash, color: '#6d28d9' },
  'identity_provider': { abbr: 'IDP', icon: Fingerprint, color: '#be123c' },
  'influxdb': { abbr: 'INX', icon: Waves, color: '#0f766e' },
  'kafka': { abbr: 'KF', icon: Layers, color: '#ea580c' },
  'kinesis': { abbr: 'KNS', icon: Wind, color: '#d97706' },
  'kubernetes': { abbr: 'K8S', icon: Container, color: '#7c3aed' },
  'leader_election': { abbr: 'LEAD', icon: Crown, color: '#6d28d9' },
  'ledger_service': { abbr: 'LDG', icon: Landmark, color: '#16a34a' },
  'llm_api': { abbr: 'LLM', icon: BrainCircuit, color: '#9333ea' },
  'llm_router': { abbr: 'RTAI', icon: Shuffle, color: '#9333ea' },
  'load_balancer': { abbr: 'LB', icon: Scale, color: '#0891b2' },
  'log_aggregator': { abbr: 'LOG', icon: ScrollText, color: '#0891b2' },
  'mcp_server': { abbr: 'MCP', icon: Blocks, color: '#9333ea' },
  'media_transcoder': { abbr: 'TRX', icon: Clapperboard, color: '#a21caf' },
  'memcached': { abbr: 'MC', icon: MemoryStick, color: '#dc2626' },
  'metrics_collector': { abbr: 'MET', icon: Gauge, color: '#0891b2' },
  'model_registry': { abbr: 'REG', icon: Package, color: '#c026d3' },
  'moderation_service': { abbr: 'MOD', icon: ShieldCheck, color: '#9333ea' },
  'mongodb': { abbr: 'MG', icon: Leaf, color: '#16a34a' },
  'mqtt_broker': { abbr: 'MQTT', icon: Satellite, color: '#db2777' },
  'mysql': { abbr: 'MY', icon: Database, color: '#059669' },
  'nats': { abbr: 'NATS', icon: RadioTower, color: '#d97706' },
  'neo4j': { abbr: 'GDB', icon: Share2, color: '#059669' },
  'object_storage': { abbr: 'OS', icon: Archive, color: '#0369a1' },
  'payment_gateway': { abbr: 'PAY', icon: CreditCard, color: '#16a34a' },
  'postgresql': { abbr: 'PG', icon: Database, color: '#0f766e' },
  'pubsub': { abbr: 'PS', icon: Radio, color: '#d97706' },
  'push_service': { abbr: 'PUSH', icon: Bell, color: '#ea580c' },
  'rabbitmq': { abbr: 'RM', icon: MessagesSquare, color: '#f59e0b' },
  'rag_pipeline': { abbr: 'RAG', icon: FileSearch, color: '#9333ea' },
  'recommendation_engine': { abbr: 'REC', icon: Sparkles, color: '#c026d3' },
  'redis': { abbr: 'RD', icon: Zap, color: '#dc2626' },
  'reranker': { abbr: 'RR', icon: ListOrdered, color: '#9333ea' },
  'reverse_proxy': { abbr: 'RP', icon: ArrowLeftRight, color: '#2563eb' },
  'saga': { abbr: 'SAGA', icon: History, color: '#64748b' },
  'secrets_manager': { abbr: 'SEC', icon: KeyRound, color: '#be123c' },
  'serverless_function': { abbr: 'FN', icon: Braces, color: '#7c3aed' },
  'service_mesh': { abbr: 'MSH', icon: Network, color: '#2563eb' },
  'sidecar': { abbr: 'SIDE', icon: Paperclip, color: '#64748b' },
  'sms_service': { abbr: 'SMS', icon: Smartphone, color: '#ea580c' },
  'spanner': { abbr: 'SPN', icon: Anchor, color: '#059669' },
  'spark': { abbr: 'SPK', icon: Flame, color: '#0d9488' },
  'sqs': { abbr: 'SQS', icon: Inbox, color: '#d97706' },
  'timescaledb': { abbr: 'TSDB', icon: Activity, color: '#059669' },
  'tool_orchestrator': { abbr: 'AGT', icon: Wrench, color: '#9333ea' },
  'tracing_collector': { abbr: 'TRC', icon: Route, color: '#0891b2' },
  'transactional_outbox': { abbr: 'OUTBOX', icon: Send, color: '#64748b' },
  'vector_database': { abbr: 'VDB', icon: Orbit, color: '#059669' },
  'waf': { abbr: 'WAF', icon: Shield, color: '#2563eb' },
  'websocket_gateway': { abbr: 'WS', icon: Plug, color: '#db2777' },
  'worker': { abbr: 'WRK', icon: Cog, color: '#4b5563' },
  'workflow_engine': { abbr: 'WF', icon: GitCommit, color: '#4338ca' },
}

export function nodeVisual(componentType: string): NodeVisual {
  return (
    NODE_VISUALS[componentType] ?? {
      abbr: componentType.slice(0, 3).toUpperCase(),
      icon: Box,
      color: '#64748b',
    }
  )
}
