# generated by datamodel-codegen:
#   filename:  challenge.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class Difficulty(Enum):
    beginner = 'beginner'
    intermediate = 'intermediate'
    advanced = 'advanced'
    expert = 'expert'


class Mode(Enum):
    challenge = 'challenge'
    repair = 'repair'
    explore = 'explore'
    interview = 'interview'


class Category(Enum):
    functional = 'functional'
    scale = 'scale'
    performance = 'performance'
    availability = 'availability'
    consistency = 'consistency'
    durability = 'durability'
    security = 'security'
    cost = 'cost'


class Priority(Enum):
    must = 'must'
    should = 'should'
    could = 'could'


class Requirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    category: Category
    description: constr(min_length=1)
    metric: str | None = None
    value: float | str | None = None
    unit: str | None = None
    priority: Priority | None = 'must'


class Severity(Enum):
    hard = 'hard'
    soft = 'soft'


class Constraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: constr(min_length=1)
    value: Any
    severity: Severity | None = 'hard'


class Chain(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    family_id: str | None = None
    level: conint(ge=1) | None = None
    next_challenge_id: str | None = None


class Challenge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-z0-9][a-z0-9\-]*$')
    title: constr(min_length=1)
    difficulty: Difficulty
    mode: Mode | None = Field(
        'challenge', description='Learning mode this challenge runs in.'
    )
    narrative: str | None = Field(
        None, description='Fictional-company scenario framing.'
    )
    requirements: list[Requirement] | None = None
    constraints: list[Constraint] | None = None
    learning_objectives: list[str] | None = None
    allowed_components: list[str] | None = Field(
        None, description='Palette restriction; empty/omitted means full catalog.'
    )
    evaluation_rules: list[constr(pattern=r'^[a-z]+\.[a-z0-9_]+$')] | None = Field(
        None, description='Subset of rule ids active for scoring this challenge.'
    )
    scenarios: list[str] | None = Field(
        None,
        description='Chaos/scenario event ids playable within this challenge (Phase 8 hooks).',
    )
    starting_graph_ref: str | None = Field(
        None,
        description='Optional golden architecture used as the starting canvas (required for repair drills).',
    )
    hints: list[str] | None = Field(
        None,
        description='Ordered hint ladder: nudge -> concept -> partial structure -> full rationale.',
    )
    ai_context_notes: str | None = Field(
        None,
        description='Extra context injected into tutor/coach prompts for this challenge.',
    )
    chain: Chain | None = Field(
        None,
        description='Progressive-chain membership (e.g. url-shortener level 2 of 6).',
        title='ChainLink',
    )
    related_topics: list[str] | None = None
    version: constr(pattern=r'^\d+\.\d+\.\d+$') | None = None
