# generated by datamodel-codegen:
#   filename:  component.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, constr


class Category(Enum):
    client = 'client'
    edge = 'edge'
    traffic = 'traffic'
    compute = 'compute'
    cache = 'cache'
    database = 'database'
    messaging = 'messaging'
    storage = 'storage'
    observability = 'observability'
    reliability = 'reliability'
    ai_genai = 'ai_genai'
    search_analytics = 'search_analytics'
    processing = 'processing'
    identity = 'identity'
    communication = 'communication'
    coordination = 'coordination'
    workflow = 'workflow'
    business = 'business'
    notifications = 'notifications'
    media = 'media'
    realtime = 'realtime'
    ml = 'ml'
    patterns = 'patterns'


class Kind(Enum):
    concept = 'concept'
    implementation = 'implementation'
    pattern = 'pattern'


class Palette(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group: str | None = None
    icon: str | None = Field(
        None, description='Icon identifier string, rendered by the frontend icon layer.'
    )
    color: constr(pattern=r'^#[0-9a-fA-F]{6}$') | None = None


class ComponentCatalogEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: constr(pattern=r'^[a-z][a-z0-9_]*$', min_length=1)
    category: Category
    kind: Kind | None = Field(
        None,
        description='Node taxonomy: concept = abstract role, implementation = concrete technology, pattern = behavioral annotation excluded from engine capacity math.',
    )
    name: constr(min_length=1)
    description: str | None = None
    version: constr(pattern=r'^\d+\.\d+\.\d+$') = Field(
        ..., description='Semver of this catalog entry.'
    )
    capabilities: list[str] | None = None
    helps_with: list[str] | None = Field(
        None,
        description='Problems this component can reduce (e.g. database_read_load).',
    )
    does_not_solve: list[str] | None = None
    risks: list[str] | None = Field(
        None, description='New concerns introduced by adding this component.'
    )
    common_patterns: list[str] | None = None
    failure_modes: list[str] | None = None
    tradeoffs: list[str] | None = None
    capacity_defaults: dict[str, Any] | None = Field(
        None,
        description='Assumed per-unit capacities (safe_reads_per_sec, safe_writes_per_sec, rps_per_instance...). Labeled assumptions; overridable per node instance.',
    )
    cost_defaults: dict[str, Any] | None = Field(
        None,
        description='Rough monthly cost estimates per unit (usd_per_unit_month). Estimates only.',
    )
    palette: Palette | None = Field(None, title='PalettePresentation')
