# generated by datamodel-codegen:
#   filename:  constraint.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, constr


class Type(Enum):
    budget = 'budget'
    data_residency = 'data_residency'
    consistency_class = 'consistency_class'
    durability = 'durability'
    compliance = 'compliance'
    operational = 'operational'
    other = 'other'


class Severity(Enum):
    hard = 'hard'
    soft = 'soft'


class Constraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-zA-Z0-9_\-.]+$', min_length=1)
    type: Type
    description: constr(min_length=1)
    value: Any | None = Field(
        None, description='Constraint value (number, string, or structured object).'
    )
    severity: Severity | None = Field(
        'hard', description='How binding the constraint is.'
    )
    metadata: dict[str, Any] | None = None
