# generated by datamodel-codegen:
#   filename:  edge.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, constr


class Direction(Enum):
    unidirectional = 'unidirectional'
    bidirectional = 'bidirectional'


class TrafficType(Enum):
    sync_request = 'sync_request'
    async_event = 'async_event'
    replication = 'replication'
    batch = 'batch'


class ArchitectureEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-zA-Z0-9_\-.]+$', min_length=1)
    source: str = Field(..., description='Id of the source ArchitectureNode.')
    target: str = Field(..., description='Id of the target ArchitectureNode.')
    direction: Direction | None = Field(
        'unidirectional',
        description='Flow direction semantics. Defaults to unidirectional source->target.',
    )
    protocol: str | None = Field(
        None, description='Optional protocol label (http, grpc, tcp, amqp, native...).'
    )
    traffic_type: TrafficType | None = Field(
        'sync_request',
        description='Semantic traffic classification used by the evaluator.',
    )
    properties: dict[str, Any] | None = Field(
        None,
        description='Edge semantics: pattern (sync|async), delivery (at_most_once|at_least_once|exactly_once), ordering, throughput hints, read/write ratio.',
    )
