# generated by datamodel-codegen:
#   filename:  scenario.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, constr


class EventType(Enum):
    db_failure = 'db_failure'
    cache_failure = 'cache_failure'
    queue_failure = 'queue_failure'
    region_outage = 'region_outage'
    network_latency = 'network_latency'
    traffic_spike = 'traffic_spike'
    hot_key = 'hot_key'
    consumer_lag = 'consumer_lag'
    dependency_outage = 'dependency_outage'
    hit_ratio_drop = 'hit_ratio_drop'
    custom = 'custom'


class AppliesTo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    component_types: list[str] | None = None


class Metric(Enum):
    availability = 'availability'
    latency_p95 = 'latency_p95'
    throughput = 'throughput'
    error_rate = 'error_rate'
    queue_depth = 'queue_depth'
    db_load = 'db_load'
    cache_hit_ratio = 'cache_hit_ratio'
    cost = 'cost'


class Change(Enum):
    increase = 'increase'
    decrease = 'decrease'
    degrade = 'degrade'
    improve = 'improve'
    none = 'none'


class ExpectedEffect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metric: Metric
    change: Change
    condition: str | None = Field(
        None,
        description="Guard expression on architecture state (e.g. 'no_failover', 'single_instance').",
    )


class ScenarioEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-z0-9][a-z0-9\-]*$')
    event_type: EventType
    title: constr(min_length=1)
    description: str | None = None
    params: dict[str, Any] | None = Field(
        None,
        description='Typed parameters per event_type (multiplier for traffic_spike, added_ms for network_latency, new_ratio for hit_ratio_drop, target_component_types...).',
    )
    applies_to: AppliesTo | None = Field(None, title='AppliesTo')
    expected_effects: list[ExpectedEffect] | None = Field(
        None,
        description='Documented expectations used in deterministic scenario fixtures (e.g. availability drops when no failover exists).',
    )
    version: constr(pattern=r'^\d+\.\d+\.\d+$') | None = None
