# generated by datamodel-codegen:
#   filename:  architecture.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr

from . import constraint, edge, node, requirement


class Group(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    name: constr(min_length=1)
    node_ids: list[str] | None = None
    properties: dict[str, Any] | None = None


class TrafficModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rps: confloat(ge=0.0) | None = None
    read_ratio: confloat(ge=0.0, le=1.0) | None = None
    write_ratio: confloat(ge=0.0, le=1.0) | None = None
    avg_request_size_bytes: confloat(ge=0.0) | None = None
    concurrency: confloat(ge=0.0) | None = None
    payload_growth_per_day_bytes: confloat(ge=0.0) | None = None
    notes: str | None = None


class Environment(Enum):
    local = 'local'
    staging = 'staging'
    production = 'production'


class DeploymentModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    environment: Environment | None = 'production'
    regions: list[str] | None = None
    multi_az: bool | None = None
    notes: str | None = None


class ArchitectureGraph(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    version: conint(ge=1) = Field(
        ..., description='Immutable architecture versions increment this counter.'
    )
    nodes: list[node.Schema]
    edges: list[edge.Schema]
    groups: list[Group] | None = Field(
        None, description='Visual/logical groupings of nodes (trust boundaries, tiers).'
    )
    requirements: list[requirement.Schema] | None = None
    constraints: list[constraint.Schema] | None = None
    traffic_model: TrafficModel | None = Field(
        None,
        description='Declared workload the architecture must handle.',
        title='TrafficModel',
    )
    deployment_model: DeploymentModel | None = Field(
        None,
        description='Where the system runs: regions, environment, cloud abstraction level.',
        title='DeploymentModel',
    )
    metadata: dict[str, Any] | None = Field(
        None,
        description='Provenance: author, challenge_id, created_at, labels. Never used by evaluators for correctness.',
    )
