# generated by datamodel-codegen:
#   filename:  architecture.schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, constr


class Position(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class Schema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-zA-Z0-9_\-.]+$', min_length=1)
    type: constr(pattern=r'^[a-z][a-z0-9_]*$', min_length=1) = Field(
        ...,
        description="Component catalog type (e.g. 'redis', 'load_balancer'). Must exist in the versioned component catalog.",
    )
    name: constr(min_length=1)
    technology: str | None = Field(
        None,
        description='Optional concrete technology label distinct from the abstract type.',
    )
    position: Position
    properties: dict[str, Any] | None = Field(
        None,
        description='Component-specific configuration (replicas, cache pattern, ttl, partition key...).',
    )
    capacity: dict[str, Any] | None = Field(
        None,
        description='Effective capacity overrides for this instance; falls back to catalog capacity_defaults.',
    )
    availability: dict[str, Any] | None = Field(
        None,
        description='Availability configuration: replicas, multi_az, multi_region, failover mode.',
    )
    deployment: dict[str, Any] | None = Field(
        None, description='Deployment placement: region, az, environment.'
    )
    metadata: dict[str, Any] | None = None
