# generated by datamodel-codegen:
#   filename:  architecture.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, constr


class Category(Enum):
    functional = 'functional'
    scale = 'scale'
    performance = 'performance'
    availability = 'availability'
    consistency = 'consistency'
    durability = 'durability'
    security = 'security'
    cost = 'cost'


class Priority(Enum):
    must = 'must'
    should = 'should'
    could = 'could'


class Schema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-zA-Z0-9_\-.]+$', min_length=1)
    category: Category
    description: constr(min_length=1)
    target: float | str | None = Field(
        None,
        description="Numeric target or symbolic target (e.g. 'strong', 'global'). Null for purely functional statements.",
    )
    unit: str | None = Field(
        None, description='Unit of the target (rps, ms, percent, usd_per_month, ...).'
    )
    priority: Priority | None = Field(
        'should', description='Weight used by scoring aggregation.'
    )
    validation_rules: list[constr(min_length=1)] | None = Field(
        None,
        description="Machine-checkable expressions, e.g. 'rps >= 100000', 'p95 <= 200ms', 'availability >= 99.99'.",
    )
